/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Zen Pro
 */
public class frmFirma extends javax.swing.JFrame {
Konekcija _db = new Konekcija();
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form frmFirma
     */
    public frmFirma() {
        initComponents();
        tabelaFirmi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLekovi = new javax.swing.JLabel();
        lblOsoblje = new javax.swing.JLabel();
        lblProdaja = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRedBr = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        txtDrzava = new javax.swing.JTextField();
        txtGod_Osn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFirma = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnIzbrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBr_tel = new javax.swing.JTextField();
        btnObrisi = new javax.swing.JButton();
        lblUloga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(43, 169, 171));

        lblLekovi.setBackground(new java.awt.Color(255, 255, 255));
        lblLekovi.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblLekovi.setForeground(new java.awt.Color(255, 255, 255));
        lblLekovi.setText("LEKOVI");
        lblLekovi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLekoviMouseClicked(evt);
            }
        });

        lblOsoblje.setBackground(new java.awt.Color(255, 255, 255));
        lblOsoblje.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblOsoblje.setForeground(new java.awt.Color(255, 255, 255));
        lblOsoblje.setText("OSOBLJE");
        lblOsoblje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOsobljeMouseClicked(evt);
            }
        });

        lblProdaja.setBackground(new java.awt.Color(255, 255, 255));
        lblProdaja.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblProdaja.setForeground(new java.awt.Color(255, 255, 255));
        lblProdaja.setText("PRODAJA");
        lblProdaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProdajaMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Asset 3.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(79, 109, 176));
        jLabel5.setText("LISTA FIRMI");

        jLabel6.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 109, 176));
        jLabel6.setText("R.BR.:");

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 109, 176));
        jLabel1.setText("NAZIV:");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 109, 176));
        jLabel2.setText("DRZAVA:");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 109, 176));
        jLabel3.setText("GOD. OSNOVANA:");

        txtRedBr.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtRedBr.setForeground(new java.awt.Color(79, 109, 176));
        txtRedBr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        txtNaziv.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtNaziv.setForeground(new java.awt.Color(79, 109, 176));
        txtNaziv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        txtDrzava.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtDrzava.setForeground(new java.awt.Color(79, 109, 176));
        txtDrzava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        txtGod_Osn.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtGod_Osn.setForeground(new java.awt.Color(79, 109, 176));
        txtGod_Osn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        tblFirma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFirmaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFirma);

        btnDodaj.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnDodaj.setForeground(new java.awt.Color(79, 109, 176));
        btnDodaj.setText("DODAJ");
        btnDodaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDodajMouseClicked(evt);
            }
        });

        btnIzbrisi.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnIzbrisi.setForeground(new java.awt.Color(79, 109, 176));
        btnIzbrisi.setText("IZBRISI");
        btnIzbrisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIzbrisiMouseClicked(evt);
            }
        });

        btnIzmeni.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(79, 109, 176));
        btnIzmeni.setText("IZMENI");
        btnIzmeni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIzmeniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIzmeniMouseEntered(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Source Sans Pro Black", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(79, 109, 176));
        jLabel9.setText("FIRMA");

        jLabel10.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(79, 109, 176));
        jLabel10.setText("PRETRAGA:");

        txtPretraga.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtPretraga.setForeground(new java.awt.Color(79, 109, 176));
        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });
        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(79, 109, 176));
        jLabel11.setText("BR. TELEFONA:");

        txtBr_tel.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtBr_tel.setForeground(new java.awt.Color(79, 109, 176));
        txtBr_tel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        btnObrisi.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnObrisi.setForeground(new java.awt.Color(79, 109, 176));
        btnObrisi.setText("OBRIŠI POLJA");
        btnObrisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObrisiMouseClicked(evt);
            }
        });

        lblUloga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUloga.setForeground(new java.awt.Color(79, 109, 176));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addComponent(txtRedBr, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblUloga)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDrzava)
                                            .addComponent(txtNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBr_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtGod_Osn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzbrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzmeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnObrisi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(logo)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(164, 164, 164)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(326, 326, 326)
                    .addComponent(jLabel9)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUloga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtRedBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGod_Osn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBr_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnIzbrisi)
                            .addComponent(btnIzmeni)
                            .addComponent(btnObrisi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel9)
                    .addContainerGap(454, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLekovi)
                .addGap(85, 85, 85)
                .addComponent(lblOsoblje)
                .addGap(85, 85, 85)
                .addComponent(lblProdaja)
                .addGap(279, 279, 279))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekovi)
                    .addComponent(lblProdaja)
                    .addComponent(lblOsoblje))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void tabelaFirmi(){
        
        try{
            
        con = _db.KonBaza();
        String sql = "Select * from apoteka.firma";
        pst =  con.prepareStatement(sql);
        rs = pst.executeQuery();
        tblFirma.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
}
    private void lblOsobljeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOsobljeMouseClicked
        // TODO add your handling code here:
        frmOsoblje osoblje = new frmOsoblje();
        osoblje.lblUloga.setText(lblUloga.getText());
        osoblje.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblOsobljeMouseClicked

    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretragaActionPerformed

    private void lblLekoviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLekoviMouseClicked
        // TODO add your handling code here:
        frmLekovi lekovi = new frmLekovi();
        lekovi.lblUloga.setText(lblUloga.getText());
        lekovi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLekoviMouseClicked

    private void lblProdajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdajaMouseClicked
        // TODO add your handling code here:
        frmProdaja prodaja = new frmProdaja();
        prodaja.lblUloga.setText(lblUloga.getText());
        prodaja.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblProdajaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        // TODO add your handling code here:
//        if (lblUloga.getText().equals("Apotekar")) {
//            btnDodaj.setVisible(false);
//            btnIzbrisi.setVisible(false);
//            btnIzmeni.setVisible(false);
//        }
    }//GEN-LAST:event_formWindowOpened

    private void btnDodajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDodajMouseClicked
        // TODO add your handling code here:
        String naziv = txtNaziv.getText();
        String drzava = txtDrzava.getText();
        String godina = txtGod_Osn.getText();   
        String br_tel = txtBr_tel.getText();
        
        if(naziv.equals("") || drzava.equals("") || godina.equals("") || br_tel.equals(""))
            {
            JOptionPane.showMessageDialog(rootPane, "Popunite sva polja!","Prazna polja",JOptionPane.WARNING_MESSAGE);   
            
           }
           
        else{
            try {
               con = _db.KonBaza();
                String sql = "INSERT INTO apoteka.firma (naziv, drzava, god_osnovana, br_tel_kompanije)VALUES (?, ?, ?,?)";
                pst =  con.prepareStatement(sql);
                pst.setString(1, txtNaziv.getText());
                pst.setString(2, txtDrzava.getText());            
                pst.setInt(3, Integer.valueOf(txtGod_Osn.getText()));
                pst.setInt(4, Integer.valueOf(txtBr_tel.getText()));

                pst.execute();
                JOptionPane.showMessageDialog(rootPane, "Uspesno ste uneli!");
                tabelaFirmi();


            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
    }//GEN-LAST:event_btnDodajMouseClicked

    private void btnIzbrisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzbrisiMouseClicked
        // TODO add your handling code here:
        if(txtRedBr.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Izaberite firmu koju zelite da izbrisete!");
        }
        else{
            try{
               con = _db.KonBaza();
               String sql="DELETE FROM apoteka.firma WHERE firma_id = '"+txtRedBr.getText()+"'";
               pst =  con.prepareStatement(sql);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(rootPane, "Uspesno ste obrisali!");
               tabelaFirmi();
            }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
    }//GEN-LAST:event_btnIzbrisiMouseClicked

    private void tblFirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFirmaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblFirma.getModel();
        int red = tblFirma.getSelectedRow();

        txtRedBr.setText(model.getValueAt(red, 0).toString());
        txtNaziv.setText(model.getValueAt(red, 1).toString());
        txtDrzava.setText(model.getValueAt(red, 2).toString());
        txtGod_Osn.setText(model.getValueAt(red, 3).toString());
        txtBr_tel.setText(model.getValueAt(red, 4).toString());
    }//GEN-LAST:event_tblFirmaMouseClicked

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        // TODO add your handling code here:
         {
        try{
            con = _db.KonBaza();
            String sql = "SELECT firma_id, naziv, drzava, god_osnovana, br_tel_kompanije FROM firma where naziv like '%"+txtPretraga.getText()+"%' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tblFirma.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }catch (Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    } 
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void btnIzmeniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzmeniMouseClicked
        // TODO add your handling code here:
           if(txtRedBr.getText().isEmpty() ||txtNaziv.getText().isEmpty() ||txtDrzava.getText().isEmpty() ||txtGod_Osn.getText().isEmpty() ||txtBr_tel.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Bezuspesno! Odaberite da biste izmenili podatke.");
        }
        else 
        {
            try 
            {
               con = _db.KonBaza();
               String sql="UPDATE apoteka.firma SET firma_id = '"+txtRedBr.getText()+"'"+",naziv = '"+txtNaziv.getText()+"'"+",drzava = '"+txtDrzava.getText()
                       +"'"+",god_osnovana = '"+txtGod_Osn.getText()+"'"+",br_tel_kompanije = '"+txtBr_tel.getText()
                       +"'"+"where firma_id = "+txtRedBr.getText();    
               
               pst =  con.prepareStatement(sql);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(rootPane, "Uspesno ste izmenili!");
               tabelaFirmi();
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
            }
            tabelaFirmi();
        }
    
    }//GEN-LAST:event_btnIzmeniMouseClicked

    private void btnIzmeniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzmeniMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzmeniMouseEntered

    private void btnObrisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObrisiMouseClicked
        // TODO add your handling code here:
        txtNaziv.setText("");
        txtDrzava.setText("");
        txtGod_Osn.setText("");
        txtBr_tel.setText("");
    }//GEN-LAST:event_btnObrisiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFirma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnIzmeni;
    public javax.swing.JButton btnObrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLekovi;
    private javax.swing.JLabel lblOsoblje;
    private javax.swing.JLabel lblProdaja;
    public javax.swing.JLabel lblUloga;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tblFirma;
    private javax.swing.JTextField txtBr_tel;
    private javax.swing.JTextField txtDrzava;
    private javax.swing.JTextField txtGod_Osn;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPretraga;
    private javax.swing.JTextField txtRedBr;
    // End of variables declaration//GEN-END:variables
}
