/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Zen Pro
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmOtvaranje
     */
    public frmLogin() {
        initComponents();
//        provera();
    }
    Konekcija _db = new Konekcija();
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

//    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblRegistruj = new javax.swing.JLabel();
        btnUloguj = new javax.swing.JButton();
        txtKorisnik = new javax.swing.JTextField();
        pswSifra = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        cmbUloga = new javax.swing.JComboBox<>();
        cbSifra = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOJ LEK APOTEKA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(250, 250));
        setMinimumSize(new java.awt.Dimension(100, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 3));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Asset 3.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 109, 176));
        jLabel2.setText("LOGIN");

        jLabel3.setBackground(new java.awt.Color(79, 109, 176));
        jLabel3.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel3.setText("Korisnicko ime:");

        jLabel4.setBackground(new java.awt.Color(79, 109, 176));
        jLabel4.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel4.setText("Sifra:");

        lblRegistruj.setFont(new java.awt.Font("Source Sans Pro Black", 2, 10)); // NOI18N
        lblRegistruj.setForeground(new java.awt.Color(204, 0, 51));
        lblRegistruj.setText("       Nemas nalog? Registruj se");
        lblRegistruj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 0, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 0, 51)));
        lblRegistruj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrujMouseClicked(evt);
            }
        });

        btnUloguj.setBackground(new java.awt.Color(79, 109, 176));
        btnUloguj.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        btnUloguj.setForeground(new java.awt.Color(255, 255, 255));
        btnUloguj.setText("Uloguj se");
        btnUloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlogujActionPerformed(evt);
            }
        });

        txtKorisnik.setBackground(new java.awt.Color(43, 169, 171));
        txtKorisnik.setForeground(new java.awt.Color(255, 255, 255));
        txtKorisnik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKorisnikKeyPressed(evt);
            }
        });

        pswSifra.setBackground(new java.awt.Color(43, 169, 171));
        pswSifra.setForeground(new java.awt.Color(255, 255, 255));
        pswSifra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswSifraKeyPressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(79, 109, 176));
        jLabel5.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel5.setText("Uloga:");

        cmbUloga.setFont(new java.awt.Font("Source Sans Pro Black", 1, 11)); // NOI18N
        cmbUloga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Odaberi", "Admin", "Apotekar" }));

        cbSifra.setText("Prikazi sifru");
        cbSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSifraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pswSifra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(txtKorisnik, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSifra))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(btnUloguj))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbUloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(123, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRegistruj, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)))))
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSifra))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUloga, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUloguj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegistruj, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(logo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  public void clearFields(String k)
    {
        txtKorisnik.setText(k);
        pswSifra.setText(k);
    }
   
   String e = "";
    private void btnUlogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlogujActionPerformed
        // TODO add your handling code here:
       
        String ime = txtKorisnik.getText().trim();
        String sifra = String.valueOf(pswSifra.getPassword());
        String uloga = cmbUloga.getSelectedItem().toString();
        
        
      try {
       con = _db.KonBaza();
       String sql = "SELECT * FROM `user` WHERE `korisnicko_ime`='"+ime+"' and `password`='"+sifra+"' and uloga='"+uloga+"'";
       PreparedStatement pst = con.prepareStatement(sql);
       ResultSet rs = pst.executeQuery();
       if(rs.next()) {
           //String u = rs.getString("naziv");
           if(uloga.equals("Admin")){
                JOptionPane.showMessageDialog(null, "Ulogovani kao Administrator!");
                frmOsoblje osoblje = new frmOsoblje();
                osoblje.setVisible(true);
                setVisible(false);
           }
           else if (uloga.equals("Apotekar")) {
            JOptionPane.showMessageDialog(null, "Ulogovani kao Apotekar!");
            frmProdaja prodaja = new frmProdaja();
            prodaja.lblUloga.setText("Apotekar");
            prodaja.setVisible(true);
            setVisible(false);
           }
           
        }
       else if(ime.equals("") || sifra.trim().equals("") || uloga.equals("Odaberi"))
            {
            JOptionPane.showMessageDialog(rootPane, "Popunite sva polja!","Prazna polja",JOptionPane.WARNING_MESSAGE);   
        }
       else {
           JOptionPane.showMessageDialog(null, "Korisnicko ime ili Password nisu ispravni!");
           txtKorisnik.setText("");
           pswSifra.setText("");
        
           
            }
       }
       catch(Exception e)
       {
                  JOptionPane.showMessageDialog(null, "Greška u komunikaciji sa bazom"+e);
       }
        clearFields(e);
    }//GEN-LAST:event_btnUlogujActionPerformed

    private void lblRegistrujMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrujMouseClicked
        // TODO add your handling code here:
        frmRegistracija registracija = new frmRegistracija();
        registracija.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegistrujMouseClicked

    private void txtKorisnikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKorisnikKeyPressed
        // TODO add your handling code here:
          if(txtKorisnik.getText().isEmpty())
        {
            txtKorisnik.requestFocus();
        }
        else{
            int key = evt.getKeyCode();
            if(key == 10){
                pswSifra.requestFocus();
            }
          }
    }//GEN-LAST:event_txtKorisnikKeyPressed

    private void pswSifraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSifraKeyPressed
        // TODO add your handling code here:
        if(String.valueOf(pswSifra.getPassword()).equals(""))
        {
            pswSifra.requestFocus();
        }
        else{
            int key = evt.getKeyCode();
            if(key==10){
                btnUloguj.doClick();
            }
        }
    }//GEN-LAST:event_pswSifraKeyPressed

    private void cbSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSifraActionPerformed
        // TODO add your handling code here:
        if(cbSifra.isSelected()){
        pswSifra.setEchoChar((char)0);
        }
    }//GEN-LAST:event_cbSifraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUloguj;
    private javax.swing.JCheckBox cbSifra;
    private javax.swing.JComboBox<String> cmbUloga;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRegistruj;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pswSifra;
    private javax.swing.JTextField txtKorisnik;
    // End of variables declaration//GEN-END:variables
}
