/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

/**
 *
 * @author Zen Pro
 */

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

public class frmLekovi extends javax.swing.JFrame {

    Konekcija _db = new Konekcija();
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    java.util.Date PDatum, IDatum;
    java.sql.Date pDatum, iDatum;
    /**
     * Creates new form frmLekovi
     */
    public frmLekovi() {
        initComponents();
        tabelaLekovi();
        comboFirma(cmbFirma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void tabelaLekovi(){
        
        try{
            
        con = _db.KonBaza();
        String sql = "Select * from apoteka.lek";
        pst =  con.prepareStatement(sql);
        rs = pst.executeQuery();
        tblLek.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
}

     public void comboFirma(JComboBox cmbFirma)
    {
        try{
            con = _db.KonBaza();
            String sql = "SELECT * FROM firma";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
                      
            
            while(rs.next())
            { 
                cmbFirma.addItem(rs.getString("naziv"));
            }
        
        } catch(Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFirma = new javax.swing.JLabel();
        lblOsoblje = new javax.swing.JLabel();
        lblProdaja = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JTextField();
        txtNazivLeka = new javax.swing.JTextField();
        txtCena = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        cmbFirma = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLek = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnIzbrisi = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        btnObrisi = new javax.swing.JButton();
        lblUloga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEKOVI");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(43, 169, 171));

        lblFirma.setBackground(new java.awt.Color(255, 255, 255));
        lblFirma.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblFirma.setForeground(new java.awt.Color(255, 255, 255));
        lblFirma.setText("FIRMA");
        lblFirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFirmaMouseClicked(evt);
            }
        });

        lblOsoblje.setBackground(new java.awt.Color(255, 255, 255));
        lblOsoblje.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblOsoblje.setForeground(new java.awt.Color(255, 255, 255));
        lblOsoblje.setText("OSOBLJE");
        lblOsoblje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOsobljeMouseClicked(evt);
            }
        });

        lblProdaja.setBackground(new java.awt.Color(255, 255, 255));
        lblProdaja.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblProdaja.setForeground(new java.awt.Color(255, 255, 255));
        lblProdaja.setText("PRODAJA");
        lblProdaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProdajaMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Asset 3.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(79, 109, 176));
        jLabel5.setText("LISTA LEKOVA");

        jLabel6.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 109, 176));
        jLabel6.setText("SIFRA:");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 109, 176));
        jLabel2.setText("NAZIV LEKA:");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 109, 176));
        jLabel3.setText("CENA:");

        jLabel4.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(79, 109, 176));
        jLabel4.setText("DATUM PROIZVODA:");

        jLabel7.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(79, 109, 176));
        jLabel7.setText("DATUM ISTEKA:");

        jLabel8.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(79, 109, 176));
        jLabel8.setText("FIRMA:");

        txtSifra.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtSifra.setForeground(new java.awt.Color(79, 109, 176));
        txtSifra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        txtNazivLeka.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtNazivLeka.setForeground(new java.awt.Color(79, 109, 176));
        txtNazivLeka.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));
        txtNazivLeka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivLekaActionPerformed(evt);
            }
        });

        txtCena.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtCena.setForeground(new java.awt.Color(79, 109, 176));
        txtCena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));
        txtCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCenaActionPerformed(evt);
            }
        });

        jDateChooser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        jDateChooser2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        cmbFirma.setFont(new java.awt.Font("Source Sans Pro Black", 1, 11)); // NOI18N
        cmbFirma.setForeground(new java.awt.Color(79, 109, 176));
        cmbFirma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Odaberi firmu" }));
        cmbFirma.setBorder(null);

        tblLek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SIFRA", "NAZIV LEKA", "CENA", "KOLICINA", "DATUM PROIZVODA", "DATUM ISTEKA", "FIRMA"
            }
        ));
        tblLek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLekMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLek);

        btnDodaj.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnDodaj.setForeground(new java.awt.Color(79, 109, 176));
        btnDodaj.setText("DODAJ");
        btnDodaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDodajMouseClicked(evt);
            }
        });

        btnIzbrisi.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnIzbrisi.setForeground(new java.awt.Color(79, 109, 176));
        btnIzbrisi.setText("IZBRISI");
        btnIzbrisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIzbrisiMouseClicked(evt);
            }
        });
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(79, 109, 176));
        btnUpdate.setText("IZMENI");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Source Sans Pro Black", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(79, 109, 176));
        jLabel9.setText("LEKOVI");

        jLabel10.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(79, 109, 176));
        jLabel10.setText("PRETRAGA:");

        txtPretraga.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtPretraga.setForeground(new java.awt.Color(79, 109, 176));
        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });
        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(79, 109, 176));
        jLabel11.setText("KOLICINA:");

        txtKolicina.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtKolicina.setForeground(new java.awt.Color(79, 109, 176));
        txtKolicina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        btnObrisi.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnObrisi.setForeground(new java.awt.Color(79, 109, 176));
        btnObrisi.setText("OBRIŠI POLJA");
        btnObrisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObrisiMouseClicked(evt);
            }
        });

        lblUloga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUloga.setForeground(new java.awt.Color(79, 109, 176));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel11))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNazivLeka)
                                            .addComponent(txtCena))
                                        .addGap(111, 111, 111))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(12, 12, 12)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(75, 75, 75)
                                                .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(244, 244, 244))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnIzbrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(btnUpdate)
                                                .addGap(18, 18, 18)))
                                        .addComponent(btnObrisi))
                                    .addComponent(lblUloga))
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(logo)
                        .addGap(19, 19, 19))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(326, 326, 326)
                    .addComponent(jLabel9)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblUloga)
                                .addGap(74, 74, 74)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtNazivLeka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtKolicina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(cmbFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnIzbrisi)
                            .addComponent(btnObrisi)
                            .addComponent(btnUpdate))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addComponent(logo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel9)
                    .addContainerGap(478, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(lblFirma)
                .addGap(85, 85, 85)
                .addComponent(lblOsoblje)
                .addGap(85, 85, 85)
                .addComponent(lblProdaja)
                .addGap(279, 279, 279))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirma)
                    .addComponent(lblProdaja)
                    .addComponent(lblOsoblje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretragaActionPerformed

    private void lblOsobljeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOsobljeMouseClicked
        // TODO add your handling code here:
        frmOsoblje osoblje = new frmOsoblje();
        osoblje.lblUloga.setText(lblUloga.getText());
        osoblje.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblOsobljeMouseClicked

    private void lblFirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFirmaMouseClicked
        // TODO add your handling code here:
        frmFirma firma = new frmFirma();
        firma.lblUloga.setText(lblUloga.getText());
        firma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFirmaMouseClicked

    private void lblProdajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdajaMouseClicked
        // TODO add your handling code here:
        frmProdaja prodaja = new frmProdaja();
        prodaja.lblUloga.setText(lblUloga.getText());
        prodaja.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblProdajaMouseClicked

    private void txtCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCenaActionPerformed

    private void txtNazivLekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivLekaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivLekaActionPerformed

    private void btnDodajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDodajMouseClicked
        // TODO add your handling code here:
        String naziv = txtNazivLeka.getText();
        String cena = txtCena.getText();
        String kolicina = txtKolicina.getText();   
        String firma = cmbFirma.getSelectedItem().toString();
        
       PDatum = jDateChooser1.getDate();
       pDatum = new java.sql.Date(PDatum.getTime());
       IDatum = jDateChooser2.getDate();
       iDatum = new java.sql.Date(IDatum.getTime());
        
       
       if(naziv.equals("") || cena.equals("") || kolicina.equals(""))
            {
            JOptionPane.showMessageDialog(rootPane, "Popunite sva polja!","Prazna polja",JOptionPane.WARNING_MESSAGE);   
            
           }
           
        else{
       
       try {
           con = _db.KonBaza();
           String sql = "INSERT INTO apoteka.lek (naziv, cena, kolicina, datum_proizvoda, datum_isteka, firma)VALUES (?, ?, ?, ?, ?,?)";
           pst =  con.prepareStatement(sql);
            
           pst.setString(1, txtNazivLeka.getText());
           pst.setInt(2, Integer.valueOf(txtCena.getText()));
           pst.setInt(3, Integer.valueOf(txtKolicina.getText()));
           pst.setDate(4, pDatum);
           pst.setDate(5, iDatum);
           pst.setString(6, cmbFirma.getSelectedItem().toString());

           pst.execute();
           JOptionPane.showMessageDialog(rootPane, "Uspesno ste uneli!");
           tabelaLekovi();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
       }
    }//GEN-LAST:event_btnDodajMouseClicked

    private void btnIzbrisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzbrisiMouseClicked
        // TODO add your handling code here:
        if(txtSifra.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Izaberite lek koji zelite da izbrisete!");
        }
        else{
            try{
               con = _db.KonBaza();
               String sql="DELETE FROM apoteka.lek WHERE lek_id = '"+txtSifra.getText()+"'";
               pst =  con.prepareStatement(sql);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(rootPane, "Uspesno ste obrisali!");
               tabelaLekovi();
            }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
    }//GEN-LAST:event_btnIzbrisiMouseClicked

    private void tblLekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLekMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblLek.getModel();
        int red = tblLek.getSelectedRow();

        txtSifra.setText(model.getValueAt(red, 0).toString());
        txtNazivLeka.setText(model.getValueAt(red, 1).toString());
        txtCena.setText(model.getValueAt(red, 2).toString());
        txtKolicina.setText(model.getValueAt(red, 3).toString());
        
    }//GEN-LAST:event_tblLekMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        if(txtSifra.getText().isEmpty() ||txtNazivLeka.getText().isEmpty() ||txtCena.getText().isEmpty() ||txtKolicina.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Bezuspesno! Odaberite da biste izmenili podatke.");
        }
        else 
        {
            try 
            {
                PDatum = jDateChooser1.getDate();
                pDatum = new java.sql.Date(PDatum.getTime());
                IDatum = jDateChooser2.getDate();
                iDatum = new java.sql.Date(IDatum.getTime());
               con = _db.KonBaza();
               String sql="UPDATE apoteka.lek SET lek_id = '"+txtSifra.getText()+"'"+",naziv = '"+txtNazivLeka.getText()+"'"
                       + ""+",cena = '"+txtCena.getText()+"'"+",kolicina = '"+txtKolicina.getText()
                       +"'"+",datum_proizvoda = '"+pDatum+"'"+",datum_isteka = '"+iDatum
                       +"'"+",firma = '"+cmbFirma.getSelectedItem().toString()+"'"+"where lek_id = "+txtSifra.getText();    
               
               pst =  con.prepareStatement(sql);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(rootPane, "Uspesno ste izmenili!");
               tabelaLekovi();
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
            }
            tabelaLekovi();
        }
    }//GEN-LAST:event_btnUpdateMouseClicked
//    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
//        // TODO add your handling code here:
//        if (lblUloga.getText().equals("Apotekar")) {
//            btnDodaj.setVisible(false);
//            btnIzbrisi.setVisible(false);
//            btnUpdate.setVisible(false);
//        }
//    }
    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        // TODO add your handling code here:
        {
        try{
            con = _db.KonBaza();
            String sql = "SELECT lek_id, naziv, cena, kolicina, datum_proizvoda, datum_isteka, firma FROM lek where naziv like '%"+txtPretraga.getText()+"%' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tblLek.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }catch (Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    } 
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzbrisiActionPerformed

    private void btnObrisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObrisiMouseClicked
        // TODO add your handling code here:
        txtNazivLeka.setText("");
        txtCena.setText("");
        txtKolicina.setText("");
        cmbFirma.setSelectedItem("");
        

    }//GEN-LAST:event_btnObrisiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLekovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLekovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLekovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLekovi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLekovi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzbrisi;
    public javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbFirma;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFirma;
    private javax.swing.JLabel lblOsoblje;
    private javax.swing.JLabel lblProdaja;
    public javax.swing.JLabel lblUloga;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tblLek;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtNazivLeka;
    private javax.swing.JTextField txtPretraga;
    private javax.swing.JTextField txtSifra;
    // End of variables declaration//GEN-END:variables
}
