/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Zen Pro
 */
public class frmOsoblje extends javax.swing.JFrame {
    
    Konekcija _db = new Konekcija();
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form frmOsoblje
     */
    
    
    
        
    
    public frmOsoblje() {
        initComponents();
        tabelaOsoblje();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFirma = new javax.swing.JLabel();
        lblLekovi = new javax.swing.JLabel();
        lblProdaja = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSifra1 = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtBrTel = new javax.swing.JTextField();
        cmbPol = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOsoblja = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnIzbrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbUloga = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtKorIme = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbSifra = new javax.swing.JCheckBox();
        pswSifra = new javax.swing.JPasswordField();
        lblUloga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(43, 169, 171));

        lblFirma.setBackground(new java.awt.Color(255, 255, 255));
        lblFirma.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblFirma.setForeground(new java.awt.Color(255, 255, 255));
        lblFirma.setText("FIRMA");
        lblFirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFirmaMouseClicked(evt);
            }
        });

        lblLekovi.setBackground(new java.awt.Color(255, 255, 255));
        lblLekovi.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblLekovi.setForeground(new java.awt.Color(255, 255, 255));
        lblLekovi.setText("LEKOVI");
        lblLekovi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLekoviMouseClicked(evt);
            }
        });

        lblProdaja.setBackground(new java.awt.Color(255, 255, 255));
        lblProdaja.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblProdaja.setForeground(new java.awt.Color(255, 255, 255));
        lblProdaja.setText("PRODAJA");
        lblProdaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProdajaMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Asset 3.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(79, 109, 176));
        jLabel5.setText("LISTA OSOBLJA");

        jLabel6.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 109, 176));
        jLabel6.setText("SIFRA:");

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 109, 176));
        jLabel1.setText("IME:");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 109, 176));
        jLabel2.setText("PREZIME:");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 109, 176));
        jLabel3.setText("BR. TEL.:");

        jLabel8.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(79, 109, 176));
        jLabel8.setText("POL:");

        txtSifra1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtSifra1.setForeground(new java.awt.Color(79, 109, 176));
        txtSifra1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        txtIme.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtIme.setForeground(new java.awt.Color(79, 109, 176));
        txtIme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        txtPrezime.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtPrezime.setForeground(new java.awt.Color(79, 109, 176));
        txtPrezime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        txtBrTel.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtBrTel.setForeground(new java.awt.Color(79, 109, 176));
        txtBrTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        cmbPol.setFont(new java.awt.Font("Source Sans Pro Black", 1, 11)); // NOI18N
        cmbPol.setForeground(new java.awt.Color(79, 109, 176));
        cmbPol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "Z" }));
        cmbPol.setBorder(null);

        tblOsoblja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SIFRA", "IME", "PREZIME", "BR. TEL.", "KORISNICKO IME", "PASSWORD", "POL", "ULOGA"
            }
        ));
        tblOsoblja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOsobljaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOsoblja);

        btnDodaj.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnDodaj.setForeground(new java.awt.Color(79, 109, 176));
        btnDodaj.setText("DODAJ");
        btnDodaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDodajMouseClicked(evt);
            }
        });

        btnIzbrisi.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnIzbrisi.setForeground(new java.awt.Color(79, 109, 176));
        btnIzbrisi.setText("IZBRISI");
        btnIzbrisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIzbrisiMouseClicked(evt);
            }
        });

        btnIzmeni.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(79, 109, 176));
        btnIzmeni.setText("IZMENI");
        btnIzmeni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIzmeniMouseClicked(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnObrisi.setForeground(new java.awt.Color(79, 109, 176));
        btnObrisi.setText("OBRIŠI POLJA");
        btnObrisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObrisiMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Source Sans Pro Black", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(79, 109, 176));
        jLabel9.setText("OSOBLJE");

        jLabel10.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(79, 109, 176));
        jLabel10.setText("PRETRAGA:");

        txtPretraga.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtPretraga.setForeground(new java.awt.Color(79, 109, 176));
        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });
        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(79, 109, 176));
        jLabel11.setText("ULOGA:");

        cmbUloga.setFont(new java.awt.Font("Source Sans Pro Black", 1, 11)); // NOI18N
        cmbUloga.setForeground(new java.awt.Color(79, 109, 176));
        cmbUloga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Apotekar" }));
        cmbUloga.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(79, 109, 176));
        jLabel4.setText("KORISNICKO IME:");

        txtKorIme.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtKorIme.setForeground(new java.awt.Color(79, 109, 176));
        txtKorIme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        jLabel7.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(79, 109, 176));
        jLabel7.setText("PASSWORD:");

        cbSifra.setText("Prikazi sifru");
        cbSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSifraActionPerformed(evt);
            }
        });

        lblUloga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUloga.setForeground(new java.awt.Color(79, 109, 176));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPrezime)
                                            .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBrTel))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addComponent(txtSifra1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnIzbrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnIzmeni)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnObrisi)
                                        .addGap(85, 85, 85))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel11))
                                                .addGap(24, 24, 24)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbPol, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbUloga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel7))
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(pswSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cbSifra))
                                                    .addComponent(txtKorIme, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblUloga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(279, 279, 279)))
                        .addComponent(logo)
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(logo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblUloga))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel9)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtSifra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtKorIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cbSifra)
                                    .addComponent(pswSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtBrTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(cmbPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(cmbUloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnIzbrisi)
                            .addComponent(btnIzmeni)
                            .addComponent(btnObrisi))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(lblFirma)
                .addGap(85, 85, 85)
                .addComponent(lblLekovi)
                .addGap(85, 85, 85)
                .addComponent(lblProdaja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirma)
                    .addComponent(lblProdaja)
                    .addComponent(lblLekovi))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void tabelaOsoblje(){
        
        try{
            
        con = _db.KonBaza();
        String sql = "Select * from apoteka.user";
        pst =  con.prepareStatement(sql);
        rs = pst.executeQuery();
        tblOsoblja.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }
    
    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretragaActionPerformed

    private void lblLekoviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLekoviMouseClicked
        // TODO add your handling code here:
        frmLekovi lekovi = new frmLekovi();
        lekovi.lblUloga.setText(lblUloga.getText());
        lekovi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLekoviMouseClicked

    private void lblFirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFirmaMouseClicked
        // TODO add your handling code here:
        frmFirma firma = new frmFirma();
        firma.lblUloga.setText(lblUloga.getText());
        firma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFirmaMouseClicked

    private void lblProdajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProdajaMouseClicked
        // TODO add your handling code here:
        frmProdaja prodaja = new frmProdaja();
        prodaja.lblUloga.setText(lblUloga.getText());
        prodaja.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblProdajaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (lblUloga.getText().equals("Apotekar")) {
            btnDodaj.setVisible(true);
            btnIzbrisi.setVisible(false);
            btnIzmeni.setVisible(false);
            tblOsoblja.setVisible(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnDodajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDodajMouseClicked
        // TODO add your handling code here:
        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String brtel = txtBrTel.getText();
        String korisnickoIme = txtKorIme.getText();
        String password = String.valueOf(pswSifra.getPassword());
        String pol = cmbPol.getSelectedItem().toString();
        String uloga = cmbUloga.getSelectedItem().toString();
        
        
        if(ime.equals("") || prezime.equals("") || brtel.equals("") || korisnickoIme.equals("") || password.equals("") || pol.equals("") || uloga.equals(""))
            {
            JOptionPane.showMessageDialog(rootPane, "Popunite sva polja!","Prazna polja",JOptionPane.WARNING_MESSAGE);   
            
           }
           
        else{
           
         try {
           String query = "INSERT INTO `user`(`ime`, `prezime`, `br_tel`, `korisnicko_ime`, `password`, `pol`, `uloga` ) VALUES (?, ?, ?, ?, ?, ?,?)";
            con = _db.KonBaza();
            pst = con.prepareStatement(query);
            pst.setString(1, txtIme.getText());
            pst.setString(2, txtPrezime.getText());
            pst.setInt(3, Integer.valueOf(txtBrTel.getText()));
            pst.setString(4, txtKorIme.getText());
            pst.setString(5, String.valueOf(pswSifra.getPassword()));
            pst.setString(6, cmbPol.getSelectedItem().toString());
            pst.setString(7,cmbUloga.getSelectedItem().toString());
            
            pst.execute();
               JOptionPane.showMessageDialog(null, "Uspesno ste dodali!");
            tabelaOsoblje();
         
                }
         catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Neuspesno!" + e);
        }
        
      
        }
        
    }//GEN-LAST:event_btnDodajMouseClicked

    private void cbSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSifraActionPerformed
        // TODO add your handling code here:
        if(cbSifra.isSelected()){
            pswSifra.setEchoChar((char)0);
        }
    }//GEN-LAST:event_cbSifraActionPerformed

    private void btnIzbrisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzbrisiMouseClicked
        // TODO add your handling code here:
        if(txtSifra1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Izaberite osoblje koji zelite da izbrisete!");
        }
        else{
            try{
               con = _db.KonBaza();
               String sql="DELETE FROM apoteka.user WHERE user_id ='"+txtSifra1.getText()+"'";
               
               pst =  con.prepareStatement(sql);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(rootPane, "Uspesno ste obrisali!");
               tabelaOsoblje();
            }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
     
    }//GEN-LAST:event_btnIzbrisiMouseClicked

    private void btnObrisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObrisiMouseClicked
        // TODO add your handling code here:
        txtIme.setText("");
        txtPrezime.setText("");
        txtBrTel.setText("");
        txtKorIme.setText("");
        pswSifra.setText("");
        cmbPol.setSelectedItem("");
        cmbUloga.setSelectedItem("");
      
        
    }//GEN-LAST:event_btnObrisiMouseClicked

    private void tblOsobljaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOsobljaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblOsoblja.getModel();
        int red = tblOsoblja.getSelectedRow();

        txtSifra1.setText(model.getValueAt(red, 0).toString());
        txtIme.setText(model.getValueAt(red, 1).toString());
        txtPrezime.setText(model.getValueAt(red, 2).toString());
        txtBrTel.setText(model.getValueAt(red, 3).toString());
        txtKorIme.setText(model.getValueAt(red, 4).toString());
        pswSifra.setText(model.getValueAt(red, 5).toString());
        cmbPol.setSelectedItem(model.getValueAt(red, 6).toString());
        cmbUloga.setSelectedItem(model.getValueAt(red, 7).toString());
    }//GEN-LAST:event_tblOsobljaMouseClicked

    private void btnIzmeniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzmeniMouseClicked
        // TODO add your handling code here:
         if(txtSifra1.getText().isEmpty() ||txtIme.getText().isEmpty() ||txtPrezime.getText().isEmpty() ||txtBrTel.getText().isEmpty()||txtKorIme.getText().isEmpty()
                 ||pswSifra.getPassword().equals("") ||cmbPol.getSelectedItem().equals("") ||cmbUloga.getSelectedItem().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Bezuspesno! Odaberite da biste izmenili podatke.");
        }
        else 
        {
            try 
            {
                
               con = _db.KonBaza();
               String sql="UPDATE apoteka.user SET user_id = '"+txtSifra1.getText()+"'"+",ime = '"+txtIme.getText()+"'"
                       + ""+",prezime = '"+txtPrezime.getText()+"'"+",br_tel = '"+txtBrTel.getText()
                       +"'"+",korisnicko_ime = '"+txtKorIme.getText()+"'"+",password = '"+pswSifra.getPassword()
                       +"'"+",pol = '"+cmbPol.getSelectedItem().toString()+"'"+",uloga = '"+cmbUloga.getSelectedItem().toString()
                       +"'"+"where user_id = "+txtSifra1.getText();    
               
               pst =  con.prepareStatement(sql);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(rootPane, "Uspesno ste izmenili!");
               tabelaOsoblje();
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
            }
            tabelaOsoblje();
        }
    }//GEN-LAST:event_btnIzmeniMouseClicked

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        // TODO add your handling code here:
        {
        try{
            con = _db.KonBaza();
            String sql = "SELECT user_id, ime, prezime, br_tel, korisnicko_ime, password, pol, uloga FROM user WHERE ime like '%"+txtPretraga.getText()+"%' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tblOsoblja.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }catch (Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    } 
    }//GEN-LAST:event_txtPretragaKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOsoblje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOsoblje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOsoblje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOsoblje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOsoblje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnIzmeni;
    public javax.swing.JButton btnObrisi;
    private javax.swing.JCheckBox cbSifra;
    private javax.swing.JComboBox<String> cmbPol;
    private javax.swing.JComboBox<String> cmbUloga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFirma;
    private javax.swing.JLabel lblLekovi;
    private javax.swing.JLabel lblProdaja;
    public javax.swing.JLabel lblUloga;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pswSifra;
    private javax.swing.JTable tblOsoblja;
    private javax.swing.JTextField txtBrTel;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKorIme;
    private javax.swing.JTextField txtPretraga;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtSifra1;
    // End of variables declaration//GEN-END:variables
}
