/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.JXFormattedTextField;

/**
 *
 * @author Zen Pro
 */
public class frmProdaja extends javax.swing.JFrame {

    Konekcija _db = new Konekcija();
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form frmProdaja
     */
    public frmProdaja() {
        initComponents();
        tabelaLekovi();
        prikaziDatum();
       
    }
    
    public void tabelaLekovi(){
        
        try{
            
        con = _db.KonBaza();
        String sql = "Select * from apoteka.lek";
        pst =  con.prepareStatement(sql);
        rs = pst.executeQuery();
        tblProdaja.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
}
    
    public void prikaziDatum() {
    
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        lblDatum.setText(s.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLekovi = new javax.swing.JLabel();
        lblOsoblje = new javax.swing.JLabel();
        lblFirma = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JTextField();
        txtKolicina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdaja = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnIsprintaj = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        lblDatum = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNazivLeka = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRacun = new javax.swing.JTextArea();
        btnObrisi = new javax.swing.JButton();
        lblUloga = new javax.swing.JLabel();
        btnIzdajR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 169, 171));

        lblLekovi.setBackground(new java.awt.Color(255, 255, 255));
        lblLekovi.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblLekovi.setForeground(new java.awt.Color(255, 255, 255));
        lblLekovi.setText("LEKOVI");
        lblLekovi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLekoviMouseClicked(evt);
            }
        });

        lblOsoblje.setBackground(new java.awt.Color(255, 255, 255));
        lblOsoblje.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblOsoblje.setForeground(new java.awt.Color(255, 255, 255));
        lblOsoblje.setText("OSOBLJE");
        lblOsoblje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOsobljeMouseClicked(evt);
            }
        });

        lblFirma.setBackground(new java.awt.Color(255, 255, 255));
        lblFirma.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        lblFirma.setForeground(new java.awt.Color(255, 255, 255));
        lblFirma.setText("FIRMA");
        lblFirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFirmaMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Asset 3.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(79, 109, 176));
        jLabel5.setText("LISTA LEKOVA");

        jLabel6.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 109, 176));
        jLabel6.setText("SIFRA:");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 109, 176));
        jLabel3.setText("KOLICINA:");

        txtSifra.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtSifra.setForeground(new java.awt.Color(79, 109, 176));
        txtSifra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        txtKolicina.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtKolicina.setForeground(new java.awt.Color(79, 109, 176));
        txtKolicina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));

        tblProdaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProdaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdajaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdaja);

        btnDodaj.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnDodaj.setForeground(new java.awt.Color(79, 109, 176));
        btnDodaj.setText("DODAJ");
        btnDodaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDodajMouseClicked(evt);
            }
        });

        btnIsprintaj.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnIsprintaj.setForeground(new java.awt.Color(79, 109, 176));
        btnIsprintaj.setText("ISPRINTAJ");
        btnIsprintaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIsprintajMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(79, 109, 176));
        jLabel10.setText("PRETRAGA:");

        txtPretraga.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtPretraga.setForeground(new java.awt.Color(79, 109, 176));
        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });

        lblDatum.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        lblDatum.setForeground(new java.awt.Color(79, 109, 176));
        lblDatum.setText("DATUM:");

        jLabel12.setFont(new java.awt.Font("Source Sans Pro Black", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(79, 109, 176));
        jLabel12.setText("RACUN");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 109, 176));
        jLabel2.setText("NAZIV LEKA:");

        txtNazivLeka.setFont(new java.awt.Font("Source Sans Pro Black", 0, 11)); // NOI18N
        txtNazivLeka.setForeground(new java.awt.Color(79, 109, 176));
        txtNazivLeka.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 2));
        txtNazivLeka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivLekaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Source Sans Pro Black", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(79, 109, 176));
        jLabel13.setText("PRODAJA");

        txtRacun.setColumns(20);
        txtRacun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRacun.setRows(5);
        txtRacun.setText("\n");
        jScrollPane2.setViewportView(txtRacun);

        btnObrisi.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnObrisi.setForeground(new java.awt.Color(79, 109, 176));
        btnObrisi.setText("OBRIŠI POLJA");
        btnObrisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObrisiMouseClicked(evt);
            }
        });

        lblUloga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUloga.setForeground(new java.awt.Color(79, 109, 176));

        btnIzdajR.setFont(new java.awt.Font("Source Sans Pro Black", 1, 14)); // NOI18N
        btnIzdajR.setForeground(new java.awt.Color(79, 109, 176));
        btnIzdajR.setText("IZDAJ RACUN");
        btnIzdajR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIzdajRMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(695, 695, 695)
                                .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNazivLeka, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblUloga)
                                            .addComponent(jLabel6))
                                        .addGap(39, 39, 39)
                                        .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnObrisi))
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(288, 288, 288)))
                .addComponent(logo)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIsprintaj)
                .addGap(63, 63, 63)
                .addComponent(btnIzdajR)
                .addGap(361, 361, 361))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(356, 356, 356)
                    .addComponent(jLabel13)
                    .addContainerGap(758, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUloga))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNazivLeka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addGap(18, 18, 18)
                                .addComponent(btnObrisi)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIsprintaj)
                    .addComponent(btnIzdajR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jLabel13)
                    .addContainerGap(559, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(675, Short.MAX_VALUE)
                .addComponent(lblLekovi)
                .addGap(85, 85, 85)
                .addComponent(lblOsoblje)
                .addGap(85, 85, 85)
                .addComponent(lblFirma)
                .addGap(279, 279, 279))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekovi)
                    .addComponent(lblFirma)
                    .addComponent(lblOsoblje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1322, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLekoviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLekoviMouseClicked
        // TODO add your handling code here:
        frmLekovi lekovi = new frmLekovi();
        lekovi.lblUloga.setText(lblUloga.getText());
        lekovi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLekoviMouseClicked

    private void lblOsobljeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOsobljeMouseClicked
        // TODO add your handling code here:
        frmOsoblje osoblje = new frmOsoblje();
        osoblje.lblUloga.setText(lblUloga.getText());
        osoblje.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblOsobljeMouseClicked

    private void lblFirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFirmaMouseClicked
        // TODO add your handling code here:
        frmFirma firma = new frmFirma();
        firma.lblUloga.setText(lblUloga.getText());
        firma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFirmaMouseClicked
//     private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
//        // TODO add your handling code here:
//        if (lblUloga.getText().equals("Apotekar")) {
//            btnDodaj.setEnabled(false);
//            btnObrisi.setEnabled(false);
//            btnIsprintaj.setEnabled(false);
//        }
//    }      
    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretragaActionPerformed

    private void txtNazivLekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivLekaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivLekaActionPerformed

    private void tblProdajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdajaMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tblProdaja.getModel();
        int red = tblProdaja.getSelectedRow();
        
        //txtSifra.setText(model.getValueAt(red, 0).toString());
        txtNazivLeka.setText(model.getValueAt(red, 1).toString());
        lek_id = Integer.valueOf(model.getValueAt(red, 0).toString());
        cena = Integer.valueOf(model.getValueAt(red, 2).toString());
        staraKolicina = Integer.valueOf(model.getValueAt(red, 3).toString());
        //txtKolicina.setText(model.getValueAt(red, 3).toString());
    }//GEN-LAST:event_tblProdajaMouseClicked
    public void update()
    {
       try 
            {
                int novaKolicina;
                novaKolicina = staraKolicina - Integer.valueOf(txtKolicina.getText());
               con = _db.KonBaza();
               String sql="UPDATE apoteka.lek SET kolicina = "+novaKolicina+""+" where lek_id = "+lek_id;    
               
               pst =  con.prepareStatement(sql);
               pst.executeUpdate();
               //JOptionPane.showMessageDialog(rootPane, "Uspesno ste izmenili!");
               
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
            }
            tabelaLekovi();
        }
           
    
    int i = 0, cena, lek_id, staraKolicina;
    private void btnDodajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDodajMouseClicked
        // TODO add your handling code here:
        if(txtNazivLeka.getText().isEmpty() || txtKolicina.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Greska! Odaberite sta zelite da ubacite u korpu.");
        }
        else {        
        i++;
        update();
         
        if(i == 1)
            {
                txtRacun.setText(txtRacun.getText()+ "     ************************** MOJ LEK APOTEKA ***************************\n     "
                + "\t SIFRA      LEK    KOLICINA   CENA   UKUPNO\n\t"
                + " "+ i+ "           "+txtNazivLeka.getText()+"    "+ txtKolicina.getText()+"      "+cena+"        "+Integer.valueOf(txtKolicina.getText())*cena+"\n\t");
            }
        else 
        {
            txtRacun.setText(txtRacun.getText()+i+ "           "+txtNazivLeka.getText()+"    "+ txtKolicina.getText()+"      "+cena+"        "+Integer.valueOf(txtKolicina.getText())*cena+"\n\t");
        }
        
        
        }
    }//GEN-LAST:event_btnDodajMouseClicked

    private void btnIsprintajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIsprintajMouseClicked
        // TODO add your handling code here:
        try{
            txtRacun.print();
        }catch (Exception e) 
        {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnIsprintajMouseClicked

    private void btnObrisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObrisiMouseClicked
        // TODO add your handling code here:
        txtNazivLeka.setText("");
        txtKolicina.setText("");
        
    }//GEN-LAST:event_btnObrisiMouseClicked

    private void btnIzdajRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzdajRMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnIzdajRMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProdaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProdaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProdaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProdaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProdaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIsprintaj;
    private javax.swing.JButton btnIzdajR;
    public javax.swing.JButton btnObrisi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblFirma;
    private javax.swing.JLabel lblLekovi;
    private javax.swing.JLabel lblOsoblje;
    public javax.swing.JLabel lblUloga;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tblProdaja;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtNazivLeka;
    private javax.swing.JTextField txtPretraga;
    private javax.swing.JTextArea txtRacun;
    private javax.swing.JTextField txtSifra;
    // End of variables declaration//GEN-END:variables
}
