/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Zen Pro
 */
public class frmRegistracija extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistracija
     */
    public frmRegistracija() {
        initComponents();
    }
    Konekcija _db = new Konekcija();
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistruj = new javax.swing.JButton();
        txtIme = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBrTel = new javax.swing.JTextField();
        pswSifra1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        cmbPol = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbUloga = new javax.swing.JComboBox<>();
        btnUloguj = new javax.swing.JButton();
        cbSifra = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRACIJA");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 109, 176), 3));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Asset 3.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 109, 176));
        jLabel2.setText("REGISTRACIJA");

        jLabel3.setBackground(new java.awt.Color(79, 109, 176));
        jLabel3.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel3.setText("Ime:");

        jLabel4.setBackground(new java.awt.Color(79, 109, 176));
        jLabel4.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel4.setText("Prezime:");

        btnRegistruj.setBackground(new java.awt.Color(79, 109, 176));
        btnRegistruj.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        btnRegistruj.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistruj.setText("Registruj se");
        btnRegistruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrujActionPerformed(evt);
            }
        });

        txtIme.setBackground(new java.awt.Color(43, 169, 171));
        txtIme.setForeground(new java.awt.Color(255, 255, 255));
        txtIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(79, 109, 176));
        jLabel5.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel5.setText("Br. Tel.:");

        txtBrTel.setBackground(new java.awt.Color(43, 169, 171));
        txtBrTel.setForeground(new java.awt.Color(255, 255, 255));
        txtBrTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrTelActionPerformed(evt);
            }
        });

        pswSifra1.setBackground(new java.awt.Color(43, 169, 171));
        pswSifra1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(79, 109, 176));
        jLabel6.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel6.setText("Korisnicko ime:");

        txtKorisnickoIme.setBackground(new java.awt.Color(43, 169, 171));
        txtKorisnickoIme.setForeground(new java.awt.Color(255, 255, 255));
        txtKorisnickoIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKorisnickoImeActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(79, 109, 176));
        jLabel7.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel7.setText("Sifra:");

        jLabel8.setBackground(new java.awt.Color(79, 109, 176));
        jLabel8.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel8.setText("Pol:");

        txtPrezime.setBackground(new java.awt.Color(43, 169, 171));
        txtPrezime.setForeground(new java.awt.Color(255, 255, 255));
        txtPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeActionPerformed(evt);
            }
        });

        cmbPol.setFont(new java.awt.Font("Source Sans Pro Black", 1, 11)); // NOI18N
        cmbPol.setForeground(new java.awt.Color(79, 109, 176));
        cmbPol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "Z" }));

        jLabel9.setBackground(new java.awt.Color(79, 109, 176));
        jLabel9.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        jLabel9.setText("Uloga:");

        cmbUloga.setFont(new java.awt.Font("Source Sans Pro Black", 1, 11)); // NOI18N
        cmbUloga.setForeground(new java.awt.Color(79, 109, 176));
        cmbUloga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Apotekar" }));
        cmbUloga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUlogaActionPerformed(evt);
            }
        });

        btnUloguj.setBackground(new java.awt.Color(79, 109, 176));
        btnUloguj.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        btnUloguj.setForeground(new java.awt.Color(255, 255, 255));
        btnUloguj.setText("Uloguj se");
        btnUloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlogujActionPerformed(evt);
            }
        });

        cbSifra.setText("Prikazi sifru");
        cbSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSifraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addComponent(jLabel6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pswSifra1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIme, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrTel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSifra))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistruj)
                        .addGap(18, 18, 18)
                        .addComponent(btnUloguj))
                    .addComponent(cmbPol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel2)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pswSifra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbSifra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistruj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUloguj)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(logo)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrujActionPerformed
        // TODO add your handling code here:
        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String brtel = txtBrTel.getText();
        String korisnickoIme = txtKorisnickoIme.getText();
        String sifra = String.valueOf(pswSifra1.getPassword());
        String pol = cmbPol.getSelectedItem().toString();
        String uloga = cmbUloga.getSelectedItem().toString();
        
        
       try{
            String query = "INSERT INTO `user`(`ime`, `prezime`, `br_tel`, `korisnicko_ime`, `password`, `pol`, `uloga` ) VALUES (?, ?, ?, ?, ?, ?,?)";
            con = _db.KonBaza();
            pst = con.prepareStatement(query);
            pst.setString(1, txtIme.getText());
            pst.setString(2, txtPrezime.getText());
            pst.setInt(3, Integer.valueOf(txtBrTel.getText()));
            pst.setString(4, txtKorisnickoIme.getText());
            pst.setString(5, String.valueOf(pswSifra1.getPassword()));
            pst.setString(6, cmbPol.getSelectedItem().toString());
            pst.setString(7,cmbUloga.getSelectedItem().toString());
            pst.executeUpdate();
        if(ime.trim().equals("") || prezime.trim().equals("") || brtel.trim().equals("") || korisnickoIme.trim().equals("") || sifra.trim().equals("") || pol.trim().equals("") || uloga.trim().equals(""))
            {
            JOptionPane.showMessageDialog(rootPane, "Popunite sva polja!","Prazna polja",JOptionPane.WARNING_MESSAGE);   
        }
           else{
           JOptionPane.showMessageDialog(null, "Registracija je uspesna!");
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Registracija je neuspesna!" + e);
        
        }
    }//GEN-LAST:event_btnRegistrujActionPerformed

    private void txtImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeActionPerformed

    private void txtBrTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrTelActionPerformed

    private void txtKorisnickoImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKorisnickoImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKorisnickoImeActionPerformed

    private void txtPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeActionPerformed

    private void cmbUlogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUlogaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUlogaActionPerformed

    private void btnUlogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlogujActionPerformed
        // TODO add your handling code here:
        frmLogin login = new frmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUlogujActionPerformed

    private void cbSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSifraActionPerformed
        // TODO add your handling code here:
        if(cbSifra.isSelected()){
        pswSifra1.setEchoChar((char)0);
        }
    }//GEN-LAST:event_cbSifraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistracija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistruj;
    private javax.swing.JButton btnUloguj;
    private javax.swing.JCheckBox cbSifra;
    private javax.swing.JComboBox<String> cmbPol;
    private javax.swing.JComboBox<String> cmbUloga;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pswSifra1;
    private javax.swing.JTextField txtBrTel;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
